services:
  admin-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENTRY_POINT: lib/admin_web_main.dart
    container_name: ateker_admin_web
    network_mode: "host"
    command: /bin/sh -c "sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  mobile-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENTRY_POINT: lib/main.dart
    container_name: ateker_mobile_pwa
    network_mode: "host"
    command: /bin/sh -c "sed -i 's/listen 80;/listen 8081;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: ateker_minio
    network_mode: "host"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --address ":9900" --console-address ":9901"
    restart: unless-stopped

volumes:
  minio_data:
