// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSDkD9vQLiJqZxkqjBPgj7nUqQeXKP0I',
    appId: '1:424055297161:web:407263028ae262b17ba258',
    messagingSenderId: '424055297161',
    projectId: 'ateker-voices-data',
    storageBucket: 'ateker-voices-data.firebasestorage.app',
    authDomain: 'ateker-voices-data.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSDkD9vQLiJqZxkqjBPgj7nUqQeXKP0I',
    appId: '1:424055297161:android:407263028ae262b17ba258',
    messagingSenderId: '424055297161',
    projectId: 'ateker-voices-data',
    storageBucket: 'ateker-voices-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7MhjRyzC7rOlHOCQ_mA9qRu4KTW2WFc',
    appId: '1:424055297161:ios:d4dff4e916f2514c7ba258',
    messagingSenderId: '424055297161',
    projectId: 'ateker-voices-data',
    storageBucket: 'ateker-voices-data.firebasestorage.app',
    iosClientId: '424055297161-8rkte9cvokiedbqac3ce97qgga40bgpf.apps.googleusercontent.com',
    iosBundleId: 'com.atekervoices.com',
  );

}